apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: codebeamer-db
  name: codebeamer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: codebeamer-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/codebeamer-default: "true"
        io.kompose.service: codebeamer-db
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: codebeamer
            - name: POSTGRESQL_PASSWORD
              value: pass
            - name: POSTGRESQL_ROOT_PASSWORD
              value: password
            - name: POSTGRESQL_USER
              value: user
          image: intland/postgres:debian-12.6.3
          name: codebeamer-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "100m" # 10% of CPU (min 13)
              memory: "2Gi" # 2000 MB (min 563)
            requests:
              cpu: "50m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: codebeamer-db-postgresql
      imagePullSecrets:
        - name: codebeamer-regcred
      restartPolicy: Always
      volumes:
        - name: codebeamer-db-postgresql
          persistentVolumeClaim:
            claimName: codebeamer-db-postgresql
status: {}
