apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: codebeamer-app
  name: codebeamer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: codebeamer-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/codebeamer-default: "true"
        io.kompose.service: codebeamer-app
    spec:
      containers:
        - env:
            - name: CB_database_JDBC_ConnectionURL
              value: jdbc:postgresql://codebeamer-db:5432/codebeamer?autoReconnect=true&zeroDateTimeBehavior=convertToNull&emulateLocators=true&characterEncoding=UTF-8&useSSL=false
            - name: CB_database_JDBC_Driver
              value: org.postgresql.Driver
            - name: CB_database_JDBC_Password
              value: pass
            - name: CB_database_JDBC_Timeout
              value: "120"
            - name: CB_database_JDBC_Username
              value: user
            - name: JVM_OPTIONS
              value: " -Djdk.tls.ephemeralDHKeySize=4096"
            - name: TOMCAT_CONNECTOR_KEYSTORE_FILE
              value: "/etc/ssl/domain.p12"
            - name: TOMCAT_CONNECTOR_KEYSTORE_PASS
              value: "Swqa1234!"
            - name: WAIT_HOSTS
              value: codebeamer-db:5432
            - name: WAIT_HOSTS_TIMEOUT
              value: "120"
          image: codebeameracr.azurecr.io/codebeamerapp:9
          name: codebeamer-app
          #command: ["sh", "-c", "cp -r /home/appuser/codebeamer/repository/config/logo/js/. /home/appuser/codebeamer/repository/config/customization/js"]
          # command: ["/bin/sh", "-c"]
          # args:
          #   - |
          #     #!/bin/sh
          #     #./run.sh
          #     #until [ -d "/home/appuser/codebeamer/repository/config/logo/js" ] && [ -d "/home/appuser/codebeamer/repository/config/customization/js" ]; do sleep 1; done
          #     #cp -r /home/appuser/codebeamer/repository/config/logo/js/. /home/appuser/codebeamer/repository/config/customization/js
          #     #cp -r /home/appuser/codebeamer/repository/config/logo/cb/. /home/appuser/codebeamer/bin
          #     #./stop
          #     echo "Copying completed"
          #     # Add more commands here if needed
          ports:
            - containerPort: 8090
              hostPort: 9000
              protocol: TCP
          resources:
            limits:
              memory: "5000Mi" # 5000 MB (min.3410)
              cpu: "5" # 5 CPU cores (min.501)
            requests:
              cpu: "2"
              memory: "3500Mi"
          volumeMounts:
            - mountPath: /etc/ssl # The mount path
              name: codebeamer-app-keystore
            - mountPath: /home/appuser/codebeamer/repository/config/logo
              name: codebeamer-app-logo
            - mountPath: /home/appuser/codebeamer/repository/docs
              name: codebeamer-app-docs
            - mountPath: /home/appuser/codebeamer/repository/search
              name: codebeamer-app-search
            - mountPath: /home/appuser/codebeamer/logs
              name: codebeamer-app-logs-volume
            - mountPath: /home/appuser/codebeamer/tomcat/tmp
              name: codebeamer-app-tomcat
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", "sleep 5"]  # Give some time for volumes to mount
      imagePullSecrets:
        - name: codebeamer-regcred
      restartPolicy: Always
      volumes:
        - name: codebeamer-app-keystore
          secret:
            secretName: codebeamer-certificate
            items:
              - key: keystore.p12
                path: domain.p12
        - name: codebeamer-app-logo
          persistentVolumeClaim:
            claimName: codebeamer-app-logo
        - name: codebeamer-app-docs
          persistentVolumeClaim:
            claimName: codebeamer-app-docs
        - name: codebeamer-app-search
          persistentVolumeClaim:
            claimName: codebeamer-app-search
        - name: codebeamer-app-logs-volume
          persistentVolumeClaim:
            claimName: codebeamer-app-logs-pvc
        - name: codebeamer-app-tomcat
          persistentVolumeClaim:
            claimName: codebeamer-app-tomcat
status: {}
